// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pfm.Database.Repositories;

#nullable disable

namespace pfm.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    partial class TransactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pfm.Database.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parentcode")
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("pfm.Database.Entities.SplitsEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("categorycode")
                        .HasColumnType("text");

                    b.Property<int>("transactionid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("categorycode");

                    b.HasIndex("transactionid");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("pfm.Database.Entities.SubCategoryEntity", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("CategoryEntitycode")
                        .HasColumnType("text");

                    b.Property<int?>("TransactionEntityid")
                        .HasColumnType("integer");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parentcode")
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.HasIndex("CategoryEntitycode");

                    b.HasIndex("TransactionEntityid");

                    b.HasIndex("TransactionId");

                    b.HasIndex("parentcode");

                    b.ToTable("SubCategories", (string)null);
                });

            modelBuilder.Entity("pfm.Database.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("beneficiaryname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("mcc")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("pfm.Models.Category", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("parentcode")
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("pfm.Models.SubCategory", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("parentcode")
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.HasIndex("TransactionId");

                    b.HasIndex("parentcode");

                    b.ToTable("SubCategory");
                });

            modelBuilder.Entity("pfm.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .HasColumnType("text");

                    b.Property<string>("beneficiaryname")
                        .HasColumnType("text");

                    b.Property<string>("direction")
                        .HasColumnType("text");

                    b.Property<string>("kind")
                        .HasColumnType("text");

                    b.Property<int?>("mcc")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("pfm.Database.Entities.SplitsEntity", b =>
                {
                    b.HasOne("pfm.Database.Entities.CategoryEntity", "CategoryEntity")
                        .WithMany()
                        .HasForeignKey("categorycode");

                    b.HasOne("pfm.Database.Entities.TransactionEntity", "TransactionEntity")
                        .WithMany()
                        .HasForeignKey("transactionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryEntity");

                    b.Navigation("TransactionEntity");
                });

            modelBuilder.Entity("pfm.Database.Entities.SubCategoryEntity", b =>
                {
                    b.HasOne("pfm.Database.Entities.CategoryEntity", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryEntitycode");

                    b.HasOne("pfm.Database.Entities.TransactionEntity", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("TransactionEntityid");

                    b.HasOne("pfm.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId");

                    b.HasOne("pfm.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("parentcode");

                    b.Navigation("Category");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("pfm.Models.SubCategory", b =>
                {
                    b.HasOne("pfm.Models.Transaction", "Transaction")
                        .WithMany("SubCategories")
                        .HasForeignKey("TransactionId");

                    b.HasOne("pfm.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("parentcode");

                    b.Navigation("Category");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("pfm.Database.Entities.CategoryEntity", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("pfm.Database.Entities.TransactionEntity", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("pfm.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("pfm.Models.Transaction", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
